"""
📦 Recrut'der - Données de test
================================
Candidats et offres fictifs pour le MVP
"""

candidats_db = {
    1: {
        "id": 1,
        "nom": "Sarah Martin",
        "email": "sarah.martin@email.com",
        "competences_techniques": ["python", "sql", "excel", "power bi", "analyse de données", "statistiques"],
        "soft_skills": ["communication", "rigueur", "travail en équipe", "curiosité"],
        "experience_annees": 3,
        "qualifications": ["licence informatique", "certification data analyst", "certification power bi"],
        "niveau_etudes": "bac+3",
        "salaire_min": 35000,
        "salaire_max": 42000,
        "localisation": "paris",
        "accept_remote": True,
        "preference_teletravail": "hybride",
        "secteurs": ["tech", "finance", "consulting"],
        "type_contrat_souhaite": ["cdi", "cdd"],
        "disponibilite": "immediate",
        "langues": ["français", "anglais"],
        "taille_entreprise_preferee": ["startup", "pme", "grand_groupe"],
    },
    2: {
        "id": 2,
        "nom": "Mehdi Benjelloun",
        "email": "mehdi.benjelloun@email.com",
        "competences_techniques": ["javascript", "typescript", "react", "node.js", "css", "git", "mongodb", "docker"],
        "soft_skills": ["travail en équipe", "autonomie", "créativité", "résolution de problèmes"],
        "experience_annees": 5,
        "qualifications": ["master informatique"],
        "niveau_etudes": "bac+5",
        "salaire_min": 45000,
        "salaire_max": 55000,
        "localisation": "lyon",
        "accept_remote": True,
        "preference_teletravail": "full_remote",
        "secteurs": ["tech", "startup", "e-commerce"],
        "type_contrat_souhaite": ["cdi"],
        "disponibilite": "1_mois",
        "langues": ["français", "anglais", "arabe"],
        "taille_entreprise_preferee": ["startup", "pme"],
    },
    3: {
        "id": 3,
        "nom": "Emma Dubois",
        "email": "emma.dubois@email.com",
        "competences_techniques": ["marketing digital", "seo", "sea", "google ads", "meta ads", "réseaux sociaux", "canva", "mailchimp"],
        "soft_skills": ["créativité", "communication", "organisation", "adaptabilité"],
        "experience_annees": 2,
        "qualifications": ["licence marketing", "certification google ads", "certification meta blueprint"],
        "niveau_etudes": "bac+3",
        "salaire_min": 30000,
        "salaire_max": 38000,
        "localisation": "bordeaux",
        "accept_remote": False,
        "preference_teletravail": "presentiel",
        "secteurs": ["marketing", "e-commerce", "média", "luxe"],
        "type_contrat_souhaite": ["cdi", "cdd"],
        "disponibilite": "immediate",
        "langues": ["français", "anglais", "espagnol"],
        "taille_entreprise_preferee": ["pme", "grand_groupe"],
    },
    4: {
        "id": 4,
        "nom": "Thomas Petit",
        "email": "thomas.petit@email.com",
        "competences_techniques": ["python", "machine learning", "deep learning", "tensorflow", "pytorch", "sql", "spark", "aws", "docker"],
        "soft_skills": ["rigueur", "curiosité", "pédagogie", "esprit analytique"],
        "experience_annees": 4,
        "qualifications": ["master data science", "doctorat mathématiques appliquées"],
        "niveau_etudes": "bac+8",
        "salaire_min": 50000,
        "salaire_max": 65000,
        "localisation": "paris",
        "accept_remote": True,
        "preference_teletravail": "hybride",
        "secteurs": ["tech", "finance", "recherche", "santé"],
        "type_contrat_souhaite": ["cdi"],
        "disponibilite": "3_mois",
        "langues": ["français", "anglais"],
        "taille_entreprise_preferee": ["startup", "grand_groupe"],
    },
    5: {
        "id": 5,
        "nom": "Léa Bernard",
        "email": "lea.bernard@email.com",
        "competences_techniques": ["gestion de projet", "agile", "scrum", "jira", "confluence", "ms project", "budget", "reporting"],
        "soft_skills": ["leadership", "communication", "négociation", "gestion du stress", "organisation"],
        "experience_annees": 6,
        "qualifications": ["master management", "certification pmp", "certification scrum master"],
        "niveau_etudes": "bac+5",
        "salaire_min": 48000,
        "salaire_max": 58000,
        "localisation": "paris",
        "accept_remote": True,
        "preference_teletravail": "hybride",
        "secteurs": ["consulting", "tech", "industrie", "banque"],
        "type_contrat_souhaite": ["cdi"],
        "disponibilite": "1_mois",
        "langues": ["français", "anglais", "allemand"],
        "taille_entreprise_preferee": ["pme", "grand_groupe"],
    },
    6: {
        "id": 6,
        "nom": "Karim Alaoui",
        "email": "karim.alaoui@email.com",
        "competences_techniques": ["java", "spring boot", "microservices", "kubernetes", "aws", "sql", "mongodb", "kafka"],
        "soft_skills": ["rigueur", "autonomie", "mentorat", "esprit d'équipe"],
        "experience_annees": 8,
        "qualifications": ["ingénieur informatique", "certification aws solutions architect"],
        "niveau_etudes": "bac+5",
        "salaire_min": 60000,
        "salaire_max": 75000,
        "localisation": "paris",
        "accept_remote": True,
        "preference_teletravail": "hybride",
        "secteurs": ["tech", "banque", "assurance"],
        "type_contrat_souhaite": ["cdi", "freelance"],
        "disponibilite": "1_mois",
        "langues": ["français", "anglais", "arabe"],
        "taille_entreprise_preferee": ["grand_groupe"],
    },
    7: {
        "id": 7,
        "nom": "Julie Moreau",
        "email": "julie.moreau@email.com",
        "competences_techniques": ["figma", "sketch", "adobe xd", "photoshop", "illustrator", "html", "css", "prototypage"],
        "soft_skills": ["créativité", "empathie", "attention au détail", "collaboration"],
        "experience_annees": 4,
        "qualifications": ["master design", "certification ux design"],
        "niveau_etudes": "bac+5",
        "salaire_min": 42000,
        "salaire_max": 52000,
        "localisation": "nantes",
        "accept_remote": True,
        "preference_teletravail": "full_remote",
        "secteurs": ["tech", "startup", "agence", "e-commerce"],
        "type_contrat_souhaite": ["cdi", "freelance"],
        "disponibilite": "immediate",
        "langues": ["français", "anglais"],
        "taille_entreprise_preferee": ["startup", "pme"],
    },
    8: {
        "id": 8,
        "nom": "Antoine Rousseau",
        "email": "antoine.rousseau@email.com",
        "competences_techniques": ["comptabilité", "fiscalité", "sage", "excel", "contrôle de gestion", "audit"],
        "soft_skills": ["rigueur", "discrétion", "organisation", "analyse"],
        "experience_annees": 7,
        "qualifications": ["dscg", "expert comptable stagiaire"],
        "niveau_etudes": "bac+5",
        "salaire_min": 45000,
        "salaire_max": 55000,
        "localisation": "lille",
        "accept_remote": False,
        "preference_teletravail": "presentiel",
        "secteurs": ["cabinet comptable", "finance", "industrie"],
        "type_contrat_souhaite": ["cdi"],
        "disponibilite": "3_mois",
        "langues": ["français", "anglais"],
        "taille_entreprise_preferee": ["pme", "grand_groupe"],
    }
}


offres_db = {
    101: {
        "id": 101,
        "titre": "Data Analyst Junior",
        "entreprise": "TechCorp",
        "description": "Rejoignez notre équipe data pour analyser les données clients.",
        "competences_requises": ["python", "sql", "excel", "analyse de données"],
        "competences_bonus": ["power bi", "tableau", "r", "statistiques"],
        "soft_skills_recherches": ["communication", "rigueur", "curiosité"],
        "experience_min": 2,
        "experience_max": 4,
        "qualifications_requises": ["licence informatique"],
        "qualifications_bonus": ["master", "certification data"],
        "niveau_etudes_min": "bac+3",
        "salaire_min": 35000,
        "salaire_max": 45000,
        "localisation": "paris",
        "remote_possible": True,
        "politique_teletravail": "hybride",
        "secteur": "tech",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "immediate",
        "langues_requises": ["français"],
        "langues_bonus": ["anglais"],
        "taille_entreprise": "grand_groupe",
    },
    102: {
        "id": 102,
        "titre": "Développeur Frontend Senior",
        "entreprise": "StartupFlow",
        "description": "Développez des interfaces modernes pour notre plateforme SaaS.",
        "competences_requises": ["javascript", "react", "css", "git"],
        "competences_bonus": ["typescript", "next.js", "testing", "node.js"],
        "soft_skills_recherches": ["autonomie", "créativité", "travail en équipe"],
        "experience_min": 4,
        "experience_max": 8,
        "qualifications_requises": [],
        "qualifications_bonus": ["master informatique", "école d'ingénieur"],
        "niveau_etudes_min": "bac+3",
        "salaire_min": 50000,
        "salaire_max": 65000,
        "localisation": "lyon",
        "remote_possible": True,
        "politique_teletravail": "full_remote",
        "secteur": "startup",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "1_mois",
        "langues_requises": ["français", "anglais"],
        "langues_bonus": [],
        "taille_entreprise": "startup",
    },
    103: {
        "id": 103,
        "titre": "Chef de Projet Digital",
        "entreprise": "ConsultPro",
        "description": "Pilotez des projets de transformation digitale.",
        "competences_requises": ["gestion de projet", "agile", "communication"],
        "competences_bonus": ["scrum", "jira", "budget", "ms project"],
        "soft_skills_recherches": ["leadership", "communication", "organisation", "négociation"],
        "experience_min": 5,
        "experience_max": 10,
        "qualifications_requises": ["master"],
        "qualifications_bonus": ["certification pmp", "prince2", "scrum master"],
        "niveau_etudes_min": "bac+5",
        "salaire_min": 50000,
        "salaire_max": 65000,
        "localisation": "paris",
        "remote_possible": True,
        "politique_teletravail": "hybride",
        "secteur": "consulting",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "1_mois",
        "langues_requises": ["français", "anglais"],
        "langues_bonus": ["allemand"],
        "taille_entreprise": "grand_groupe",
    },
    104: {
        "id": 104,
        "titre": "Machine Learning Engineer",
        "entreprise": "AI Factory",
        "description": "Développez des modèles ML pour des applications de pointe.",
        "competences_requises": ["python", "machine learning", "sql", "deep learning"],
        "competences_bonus": ["tensorflow", "pytorch", "docker", "aws", "spark"],
        "soft_skills_recherches": ["rigueur", "curiosité", "pédagogie"],
        "experience_min": 3,
        "experience_max": 6,
        "qualifications_requises": ["master data science"],
        "qualifications_bonus": ["doctorat", "publications"],
        "niveau_etudes_min": "bac+5",
        "salaire_min": 55000,
        "salaire_max": 75000,
        "localisation": "paris",
        "remote_possible": True,
        "politique_teletravail": "hybride",
        "secteur": "tech",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "flexible",
        "langues_requises": ["anglais"],
        "langues_bonus": ["français"],
        "taille_entreprise": "startup",
    },
    105: {
        "id": 105,
        "titre": "Chargé Marketing Digital",
        "entreprise": "MediaPlus",
        "description": "Gérez nos campagnes marketing et réseaux sociaux.",
        "competences_requises": ["marketing digital", "réseaux sociaux", "seo"],
        "competences_bonus": ["google ads", "meta ads", "mailchimp", "canva"],
        "soft_skills_recherches": ["créativité", "communication", "adaptabilité"],
        "experience_min": 1,
        "experience_max": 3,
        "qualifications_requises": ["licence marketing"],
        "qualifications_bonus": ["certification google", "certification meta"],
        "niveau_etudes_min": "bac+3",
        "salaire_min": 28000,
        "salaire_max": 38000,
        "localisation": "bordeaux",
        "remote_possible": False,
        "politique_teletravail": "presentiel",
        "secteur": "média",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "immediate",
        "langues_requises": ["français"],
        "langues_bonus": ["anglais", "espagnol"],
        "taille_entreprise": "pme",
    },
    106: {
        "id": 106,
        "titre": "Architecte Java Senior",
        "entreprise": "BankTech",
        "description": "Concevez l'architecture de nos systèmes bancaires.",
        "competences_requises": ["java", "spring boot", "microservices", "sql"],
        "competences_bonus": ["kubernetes", "aws", "kafka", "mongodb", "docker"],
        "soft_skills_recherches": ["rigueur", "mentorat", "communication"],
        "experience_min": 7,
        "experience_max": 12,
        "qualifications_requises": ["ingénieur informatique"],
        "qualifications_bonus": ["certification aws", "certification java"],
        "niveau_etudes_min": "bac+5",
        "salaire_min": 65000,
        "salaire_max": 85000,
        "localisation": "paris",
        "remote_possible": True,
        "politique_teletravail": "hybride",
        "secteur": "banque",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "1_mois",
        "langues_requises": ["français", "anglais"],
        "langues_bonus": [],
        "taille_entreprise": "grand_groupe",
    },
    107: {
        "id": 107,
        "titre": "UX/UI Designer",
        "entreprise": "DesignStudio",
        "description": "Créez des expériences utilisateur exceptionnelles.",
        "competences_requises": ["figma", "prototypage", "ux design"],
        "competences_bonus": ["sketch", "adobe xd", "html", "css", "illustrator"],
        "soft_skills_recherches": ["créativité", "empathie", "collaboration"],
        "experience_min": 3,
        "experience_max": 6,
        "qualifications_requises": [],
        "qualifications_bonus": ["master design", "certification ux"],
        "niveau_etudes_min": "bac+3",
        "salaire_min": 40000,
        "salaire_max": 55000,
        "localisation": "paris",
        "remote_possible": True,
        "politique_teletravail": "full_remote",
        "secteur": "agence",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "immediate",
        "langues_requises": ["français"],
        "langues_bonus": ["anglais"],
        "taille_entreprise": "pme",
    },
    108: {
        "id": 108,
        "titre": "Contrôleur de Gestion",
        "entreprise": "IndustrieFrance",
        "description": "Pilotez le contrôle de gestion et les reportings.",
        "competences_requises": ["contrôle de gestion", "excel", "reporting", "budget"],
        "competences_bonus": ["sap", "power bi", "sql", "audit"],
        "soft_skills_recherches": ["rigueur", "analyse", "organisation"],
        "experience_min": 5,
        "experience_max": 10,
        "qualifications_requises": ["dscg"],
        "qualifications_bonus": ["master finance", "cca"],
        "niveau_etudes_min": "bac+5",
        "salaire_min": 50000,
        "salaire_max": 65000,
        "localisation": "lille",
        "remote_possible": False,
        "politique_teletravail": "presentiel",
        "secteur": "industrie",
        "type_contrat": "cdi",
        "date_debut_souhaitee": "3_mois",
        "langues_requises": ["français"],
        "langues_bonus": ["anglais"],
        "taille_entreprise": "grand_groupe",
    }
}


def get_next_candidat_id():
    return max(candidats_db.keys()) + 1 if candidats_db else 1


def get_next_offre_id():
    return max(offres_db.keys()) + 1 if offres_db else 101
